name: Publish PyCon DEV

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Domain
        run: |
          echo 'develop.python.co' > src/static/CNAME
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-repo: website-develop
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
